name: middle child
favicon: null
layout_spectrum: 0.70462
typography_spectrum: 0.57631
title: middlechild
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8495054708328098
  lightness: 0.125
  saturation: 0.4770554811693728
  rhythmicContrast: 0.5
purpose: []
